# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 04:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComUser',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('contact', models.IntegerField()),
                ('postcode', models.IntegerField()),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('who', models.CharField(max_length=100)),
                ('orderText', models.CharField(max_length=100)),
                ('leadTime', models.CharField(max_length=100)),
                ('enquiryId', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('timeofEnquiry', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Enquiry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ToolsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steel', models.TextField(blank=True, db_column='Steel', null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('din', models.TextField(blank=True, db_column='DIN', null=True)),
                ('assab', models.TextField(blank=True, db_column='ASSAB', null=True)),
                ('aisi', models.TextField(blank=True, db_column='AISI', null=True)),
                ('jis', models.TextField(blank=True, db_column='JIS', null=True)),
                ('availablein', models.TextField(blank=True, db_column='AvailableIn', null=True)),
                ('imagelinks', models.TextField(blank=True, db_column='imagelinks', max_length=400, null=True)),
            ],
            options={
                'db_table': 'ToolsInfo',
                'managed': True,
            },
        ),
    ]
